### ISSUE TITLE
[BUG]nauc() function

### ISSUE THREAD

**Issue by ofleitas** [albertopessia/drda#4]
Hello 

I am trying to use the nauc() function but get the following message 

Error in if (tmp < xlim[2]) { : missing value where TRUE/FALSE needed
In addition: Warning message:
In log((ylim[2] - alpha)/(beta - ylim[2])) : NaNs produced.

**Comment by albertopessia** [comment]
In order to debug the code I need to know first the parameters you used.

What are the values of `xlim`, `ylim`, and the model coefficients (you can extract them with `coef(your_drda_fit_object)`)? Is the model a 4-parameter logistic function?

**Comment by ofleitas** [comment]
Hello

I plotted with the default parameters. Looking at the graph I think that
xlim is (-2,2) (this is log(dose)) and the ylim (0,100) (This is in
percent).  The model is a 4-parameter logistic function and the coefficient
are

alpha       beta        eta        phi
 9.4002937 99.9950666  4.7709601 -0.7728488

**Comment by albertopessia** [comment]
The bug was in the specification of the `ylim` argument. By default `ylim` is defined for a relative scale of `c(0, 1)` instead of a percentage of `c(0, 100)`.

Since the curve in this example is defined for percentages with values in `c(9.4, 99.995)`, it does not intersect in this particular case the default range `c(0, 1)`. Therefore, inner computations failed with a logarithm of a negative number.

I now fixed the bug by adding extra checks in the latest 2.0 version. CRAN version is coming soon but it is possible to install the development version through GitHub (see README in the homepage).

However, if your data represent percentages, remember to set `ylim = c(0, 100)` when calling `nauc()` and `naac()`.

**Note**: New 2.0 version has a slightly different parameterization from before. Instead of a lower bound (alpha) and upper bound (beta) parameters, we now use the same parameterization of the Emax model, that is the value at -Inf (alpha) and the maximum effect at Inf (delta) (check `help(drda)` to know more).
